"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = '▶▶ '

[aws]
disabled = false
symbol = "aws:"
format = "[$symbol$profile]($style)"

[buf]
disabled = true

[cmd_duration]
disabled = false
min_time = 4_000
show_notifications = true
min_time_to_notify = 6_000

[directory]
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
'/Volumes/network/path' = '/net'

[line_break]
disabled = false

[golang]
symbol = "go:"

[gcloud]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false
symbol = "k:"
format =	'[$symbol$context(\($namespace\))]($style) in '
style = "blue"

[nodejs]
disabled = true

[package]
disabled = true

[python]
symbol = "py:"

[time]
disabled = false
format = "[$time]($style) "
style = "bold black"

[terraform]
symbol = "tf:"
format = "[$symbol$version]($style) "
