"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = '▶▶ '

[aws]
disabled = true

[buf]
disabled = true

[cmd_duration]
disabled = false
min_time = 4_000
show_notifications = true
min_time_to_notify = 6_000

[directory]
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
'/Volumes/network/path' = '/net'
'src/com/long/java/path' = 'mypath'

[line_break]
disabled = false

[golang]
symbol = "go:"

[gcloud]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false
symbol = "k:"
style = "blue"

[nodejs]
disabled = true

[package]
disabled = true

[python]
symbol = "py:"

[time]
disabled = false
format = "[$time]($style) "
style = "bold black"

[terraform]
format = "[$symbol$workspace/$version]($style) "
