add_newline = true

[aws]
disabled = true

[buf]
disabled = true

[cmd_duration]
disabled = false
min_time = 4000

[directory]
truncation_length = 3

[line_break]
disabled = false

[golang]
symbol = "go:"
# symbol = "ﳑ "

[gcloud]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = false
symbol = "k:"
style = "blue"

[nodejs]
disabled = true

[package]
disabled = true

[python]
symbol = "py:"

[time]
disabled = false
format = "[$time]($style) "
style = "bold black"

[terraform]
format = "[$symbol$workspace/$version]($style) "
