http:
  routers:
    jenkins-router:
      rule: "Host(`jenkins`, `mr-0xg1`, `mr-0xc`)"
      service: jenkins

  services:
    jenkins:
      loadBalancer:
        servers:
          - url: http://172.17.2.101:8080/
