kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  EphemeralContainers: true
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
        ---
        kind: ClusterConfiguration
        apiVersion: kubeadm.k8s.io/v1beta2
        controllerManager:
          extraArgs:
            controllers: "*,bootstrapsigner,tokencleaner,-csrcleaner,-csrsigning"

    extraPortMappings:
      - containerPort: 30080
        hostPort: 80
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
      - containerPort: 30900
        hostPort: 9000
        protocol: TCP
