dictionaries = [
    "en_us",
    "en_gb",
    "cs",
]
words = [
    "HCL",
    "Kubernetes",
    "Tmpfs",
    "appstore",
    "dkr",
    "dsn",
    "ecr",
    "errassert",
    "fieldmask",
    "policyserver",
    "sqlx",
    "sslmode",
    "svc",
]
