dictionaries = [
    "en_us",
    "en_gb",
    "cs",
]
words = [
    "Deleter",
    "Getters",
    "Kubernetes",
    "Tmpfs",
    "appstore",
    "errassert",
    "fieldmask",
    "foobars",
    "grpchealth",
    "policyserver",
    "sslmode",
    "unkeyed",
    "zoido",
]
min_word_length = 5
