dictionaries = [
    "en_us",
    "en_gb",
    "cs",
]
words = [
    "Deleter",
    "HCL",
    "IAM",
    "Kubernetes",
    "Nats",
    "Newf",
    "Tmpfs",
    "appstore",
    "bld",
    "dkr",
    "dsn",
    "ecr",
    "errassert",
    "fieldmask",
    "foobars",
    "grp",
    "grpchealth",
    "policyserver",
    "prg",
    "sqlx",
    "sslmode",
    "svc",
    "unkeyed",
]
