theme = "catppuccin_macchiato"

[editor]
color-modes = true
cursorline = true
rulers = [80, 100, 120]
trim-trailing-whitespace = true
true-color = true

[editor.auto-save]
after-delay.enable = true
focus-lost = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"[" = { "[" = "select_prev_sibling" }
"]" = { "]" = "select_next_sibling" }

S-up = "select_line_above"
S-down = "select_line_below"

[keys.normal.space.space]
# Custom shortcuts.

q = ":quit"
w = ":w"
f = ":format"
R = [":reload-all", ":config-reload", ":lsp-restart"]

"/" = ":sh zellij run --stacked -c -- scooter > /dev/null" # Run scooter (find and replace).
L = ":sh zellij run --floating -c -- lf $(dirname %{buffer_name}) > /dev/null" # Open lf in the dir of current buffer.
l = ":sh zellij run --floating -c -- lf > /dev/null" # Open lf.

k = "remove_selections" # Default binding conflicts with zellij.

[keys.select.space.space]
k = "remove_selections" # Default binding conflicts with zellij.


[keys.select.space.space.r]
# Rendering.

w = ":toggle whitespace.render all none" # On/Off whitespace rendering.
z = ":toggle soft-wrap.enable"           # On/Off soft-wrap.

[keys.normal.space.space.g]
# Git helpers

g = ":sh zellij run --stacked -c -- gitu > /dev/null"
B = ":sh zellij run --stacked -c -- gitu blame %{buffer_name} > /dev/null"
b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"


[keys.normal.space.q]
# Close.

q = ":quit"
a = ":quit-all"
x = ":write-quit"
X = ":write-quit-all"

