theme = "monokai_pro_octagon"

[editor]
color-modes = true
cursorline = true
true-color = true

[editor.auto-save]
after-delay.enable = true
focus-lost = true

[keys.normal]
"[" = {"[" = "select_prev_sibling"}
"]" = {"]" = "select_next_sibling"}
