theme = "monokai_pro_octagon"

[editor]
true-color = true
cursorline = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[keys.normal]
"[" = { "[" = "select_prev_sibling" }
"]" = { "]" = "select_next_sibling" }
