winget install -e --source winget --id "AgileBits.1Password.CLI"
winget install -e --source winget --id "AgileBits.1Password"
winget install -e --source winget --id "astral-sh.uv"
winget install -e --source winget --id "AutoHotkey.AutoHotkey"
winget install -e --source winget --id "Espanso.Espanso"
winget install -e --source winget --id "Git.Git"
winget install -e --source winget --id "GoLang.Go"
winget install -e --source winget --id "M2Team.NanaZip"
winget install -e --source winget --id "Microsoft.PowerToys"
winget install -e --source winget --id "Microsoft.VisualStudioCode.CLI"
winget install -e --source winget --id "Microsoft.VisualStudioCode"
winget install -e --source winget --id "Microsoft.WindowsTerminal"
winget install -e --source winget --id "Microsoft.WSL"
winget install -e --source winget --id "Mozilla.Firefox"
winget install -e --source winget --id "Obsidian.Obsidian"
winget install -e --source winget --id "Qalculate.Qalculate"
winget install -e --source winget --id "SumatraPDF.SumatraPDF"
winget install -e --source winget --id "Wilfred.difftastic"
winget install -e --source winget --moniker "python3"

@REM Don't exit with error when there's not update for the last package.
exit 0
