pager:
  diff: diffnav

prSections:
  - title: My
    filters: is:open author:@me
  - title: Review Requested
    filters: is:open review-requested:@me

repoPaths:
  h2oai/*: ~/dev/h2o.ai/*
  zoido/*: ~/dev/zoido/*

keybindings:
  prs:
    - key: T
      name: Actions
      command: gh enhance -R {{.RepoName}} {{.PrNumber}}
    - key: M
      name: Auto Merge
      command: gh pr merge {{.PrNumber}} --repo {{.RepoName}} --auto --squash
    - key: B
      name: Create Review Branch
      command: >
        zellij run -c --cwd "{{.RepoPath}}" -- wt switch lp/review/{{.HeadRefName}} --create --base {{.HeadRefName}}
    - key: z
      name: PR Shell
      command: >
        zellij run -c --cwd {{.RepoPath}} -- wt switch pr:{{.PrNumber}} -x fish
    - key: Z
      name: Review Branch Shell
      command: >
        zellij run -c --cwd {{.RepoPath}} -- wt switch lp/review/{{.HeadRefName}} -x fish
