pager:
  diff: diffnav

prSections:
  - title: Review Requested
    filters: is:open review-requested:@me
  - title: RR (dependabot)
    filters: is:open review-requested:@me author:dependabot[bot]
  - title: My
    filters: is:open author:@me

repoPaths:
  h2oai/*: ~/dev/h2o.ai/*
  zoido/*: ~/dev/zoido/*

keybindings:
  prs:
    - key: T
      name: Actions
      command: gh enhance -R {{.RepoName}} {{.PrNumber}}
    - key: M
      name: Auto Merge
      command: >
        zellij run -c --floating --cwd {{.RepoPath}} --
        fish -c "
        gum confirm --default=no 'Auto merge PR {{.PrNumber}}?'
        && gh pr merge {{.PrNumber}} --repo {{.RepoName}} --auto --squash
        "
    - key: V
      name: Approve & Auto Merge
      command: >
        zellij run -c --floating --cwd {{.RepoPath}} --
        fish -c "
        gum confirm --default=no 'Approve & auto merge PR {{.PrNumber}}?'
        && gh pr merge {{.PrNumber}} --repo {{.RepoName}} --auto --squash
        && gh pr review {{.PrNumber}} --repo {{.RepoName}} --approve
        "
    - key: z
      name: PR Branch Shell
      command: >
        cd {{.RepoPath}};
        git fetch {{.HeadRefName}};
        zellij run -c --cwd {{.RepoPath}} -- fish -c "wt switch {{.HeadRefName}} -x fish" > /dev/null
    - key: Z
      name: Review Branch Shell
      command: >
        cd {{.RepoPath}};
        git fetch {{.HeadRefName}};
        wt switch -C {{.RepoPath}} --create lp/review/{{.HeadRefName}} --base {{.HeadRefName}} &> /dev/null;
        zellij run -c --cwd {{.RepoPath}} -- fish -c "wt switch lp/review/{{.HeadRefName}} -x fish" > /dev/null
